# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'Windows-2019'

variables:
  solution: '**/src/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 3.0'
  inputs:
    version: '3.0.100-preview6-011799'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.0.0'
  inputs:
    versionSpec: 5.0.0
    checkLatest: true

- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config

- task: VSBuild@1
  displayName: 'Build solution **\src\*.sln'
  inputs:
    vsVersion: 'latest'
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: FileTransform@1
  displayName: 'File Transform: '
  inputs:
    folderPath: templates\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template\content\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template.csproj
    fileType: xml
	
- script: nuget pack templates\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template.nuspec -Version $(Build.BuildNumber)

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\bin\$(BuildConfiguration)\*.nupkg
     *Template.nupkg
     **\TestResults\**\*.coverage
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'